Solutions: Go for Web Development
polaris1119/golangclub pull request #22
Opened 2019-11-21 13:26 UTC by georgehao

Go for Web Development的翻译

2019-11-21 23:45 UTC, unknwon commented on template/solutions/webdev.html
> +{{define "title"}}Go Web 开发 - golangclub.com{{end}}
额 这个文件的源文件为啥子咱们仓库没有？

2019-11-22 02:13 UTC, georgehao commented on template/solutions/webdev.html
> +{{define "title"}}Go Web 开发 - golangclub.com{{end}}
确实没有，我从go.dev的`查看源码`拷贝过来的

2019-11-22 02:20 UTC, unknwon requested changes

2019-11-22 02:20 UTC, unknwon commented on template/solutions/webdev.html
> +		<p> Go 旨在使开发人员能够快速开发可扩展的、安全的 Web 应用程序。Go 标准库看自带易用的、安全的、性能好、鲁棒的 Web 服务器，以及 Web 模板库。Go 完美支持了所有的新技术， 比如：<a
```suggestion
		<p> Go 旨在使开发人员能够快速开发可扩展的、安全的 Web 应用程序。Go 标准库看自带易用的、安全的、高性能的、稳健的 Web 服务器，以及 Web 模板库。Go 完美支持了所有的新技术， 比如：<a
```

2019-11-22 02:20 UTC, unknwon commented on template/solutions/webdev.html
> +				href="https://pkg.golangclub.com/net/http" rel="noreferrer" target="_blank">HTTP/2</a>，各种流行的数据库，包括<a
golangclub 目前还不支持 pkg 浏览，我觉得要不还是先指向 pkg.go.dev 吧?

2019-11-22 02:20 UTC, unknwon commented on template/solutions/webdev.html
> +				target="_blank"> TLS 1.3</a> 等等。由于 Go 具有极好的可移植性，所以 Go Web 应用程序可以运行在任何的环境、云、操作系统上</p>
```suggestion
				target="_blank"> TLS 1.3</a> 等等。由于 Go 具有极好的可移植性，所以 Go Web 应用程序可以运行在任何的环境、云平台和操作系统上</p>
```

2019-11-22 02:20 UTC, unknwon commented on template/solutions/webdev.html
> +				Smith </a>写道：“如果你正在为网络编程，移动开发，微服务，ERP 系统寻找强力的工具，根据很多真实的 case 证明，进行相同类型的任务开发，使用 Go 进行 Web 开发比 Python 要快很多”</p>
```suggestion
				Smith </a>写道：“如果你正在为网络编程，移动开发，微服务，ERP 系统寻找强力的工具，根据很多真实的案例证明，进行相同类型的任务开发，使用 Go 进行 Web 开发比 Python 要快很多”</p>
```

2019-11-22 02:20 UTC, unknwon commented on template/solutions/webdev.html
> +			<li><a href="http://www.gorillatoolkit.org/" rel="noreferrer" target="_blank">Gorilla</a> ，一个 Go Web 编程工具包。这个工具包提供 Router、Dispatcher、Context、 RPC、Schema、Sessions、Webscoket等等</li>
没有 Macaron 嘛 😭 好歹也有 2% 的 gopher 拿来开发呢 https://www.jetbrains.com/research/devecosystem-2018/go/

2019-11-22 02:20 UTC, unknwon commented on template/solutions/webdev.html
> +			<li><a href="https://pingcap.com/index.html" rel="noreferrer" target="_blank">TIDB</a> 国内 PingCAP 团队开发的一个分布式 NewSQL 数据库
```suggestion
			<li><a href="https://pingcap.com/index.html" rel="noreferrer" target="_blank">TiDB</a> 国内 PingCAP 团队开发的一个分布式 NewSQL 数据库
```

2019-11-22 02:30 UTC, georgehao commented on template/solutions/webdev.html
> +				href="https://pkg.golangclub.com/net/http" rel="noreferrer" target="_blank">HTTP/2</a>，各种流行的数据库，包括<a
ok

2019-11-22 02:38 UTC, georgehao commented on template/solutions/webdev.html
> +			<li><a href="http://www.gorillatoolkit.org/" rel="noreferrer" target="_blank">Gorilla</a> ，一个 Go Web 编程工具包。这个工具包提供 Router、Dispatcher、Context、 RPC、Schema、Sessions、Webscoket等等</li>
好的， 那就吧`Buffalo`，`Macaron`， `revel`加上

2019-11-22 02:39 UTC, unknwon commented on template/solutions/webdev.html
> +			<li><a href="http://www.gorillatoolkit.org/" rel="noreferrer" target="_blank">Gorilla</a> ，一个 Go Web 编程工具包。这个工具包提供 Router、Dispatcher、Context、 RPC、Schema、Sessions、Webscoket等等</li>
![](https://media1.giphy.com/media/3o7qE2VAxuXWeyvJIY/giphy.gif?cid=5a38a5a294a39bce20d528ffba929c387ab532285d7e1e57&rid=giphy.gif)

2019-11-22 03:05 UTC, unknwon commented
修改完了记得 re-request review

![Screen Shot 2019-11-21 at 7 04 52 PM](https://user-images.githubusercontent.com/2946214/69394755-cdc12580-0c91-11ea-91d8-f94a4c12c29b.png)

2019-11-22 03:17 UTC, georgehao commented
> 修改完了记得 re-request review
> 
> ![Screen Shot 2019-11-21 at 7 04 52 PM](https://user-images.githubusercontent.com/2946214/69394755-cdc12580-0c91-11ea-91d8-f94a4c12c29b.png)

done

2019-11-22 03:18 UTC, unknwon approved these changes

2019-11-22 03:18 UTC, merged

2019-11-22 03:18 UTC, unknwon commented
![](https://media2.giphy.com/media/d4bmfJacxuPR3TSU/giphy.gif?cid=5a38a5a2d42f3144e88e48f447fd2d52d5e55bc1150887f3&rid=giphy.gif)