【TODO】翻译：Command-line Interfaces #20
polaris1119/golangclub pull request #24
Opened 2019-11-22 05:57 UTC by stayfoo

【TODO】翻译：Command-line Interfaces #20
https://github.com/polaris1119/golangclub/issues/20

2019-11-22 06:07 UTC, unknwon requested changes
额，我觉得 CLI 的用法有点乱，要不就统称为 CLI，要不就统称为命令行接口/程序。

2019-11-22 06:07 UTC, unknwon commented on .gitignore
> +go.sum
这一行不对吧。。这个文件是需要的

2019-11-22 06:07 UTC, unknwon commented on template/index.html
> +                    Command-line
为什么多出来了一行内容？

2019-11-22 06:07 UTC, unknwon commented on template/solutions/clis.html
> +{{define "title"}}Go 写的命令行接口 (CLIs, Command-line Interfaces)— Go语言俱乐部{{end}}
```suggestion
{{define "title"}}Go 写的命令行接口（CLIs, Command-line Interfaces）— Go语言俱乐部{{end}}
```

2019-11-22 06:07 UTC, unknwon commented on template/index.html
> +                    使用 Go 的一些流行的开源包，以及健壮的标准库， 创建快速、优雅的 CLIs (Command-line Interfaces, 命令行接口)。
```suggestion
                    使用 Go 的一些流行的开源包，以及健壮的标准库， 创建快速、优雅的命令行接口（Command-line Interfaces）。
```

2019-11-22 06:07 UTC, unknwon commented on template/solutions/clis.html
> +        <p>CLIs（CLIs, Command-line Interfaces，命令行接口）与 GUIs（GUIs，graphical user interfaces，图形用户界面）不同，CLIs 是纯文本的。云计算和基础架构程序具有易于自动化和远程功能的特性，所以云计算和基础架构程序主要是基于 CLI 的。</p>
```suggestion
        <p>命令行接口（Command-line Interfaces）与图形用户界面（Graphical User Interfaces）不同，命令行接口是纯文本的。云计算和基础架构程序具有易于自动化和远程功能的特性，所以云计算和基础架构程序主要是基于命令行接口的。</p>
```

2019-11-22 07:43 UTC, stayfoo commented on .gitignore
> +go.sum
有 go.mod 了 ，vendor 和go.sum可以不要了吧，都可以根据 go.mod 自动生成吧

2019-11-22 07:46 UTC, unknwon commented on .gitignore
> +go.sum
go.sum 是要一起 commit的

2019-11-22 07:55 UTC, stayfoo commented on template/solutions/clis.html
> +{{define "title"}}Go 写的命令行接口 (CLIs, Command-line Interfaces)— Go语言俱乐部{{end}}
> CLI

都统一成 CLI 吧

2019-11-22 07:56 UTC, unknwon commented on template/solutions/clis.html
> +{{define "title"}}Go 写的命令行接口 (CLIs, Command-line Interfaces)— Go语言俱乐部{{end}}
我觉得OK👍🏿

2019-11-22 08:05 UTC, stayfoo commented on template/index.html
> +                    Command-line
估计是电脑卡了 😆

2019-11-22 08:10 UTC, stayfoo commented on .gitignore
> +go.sum
查了一下 go.sum 的作用，之前理解有问题，以为作用是lock文件。

2019-11-22 08:22 UTC, stayfoo commented on template/solutions/clis.html
> +{{define "title"}}Go 写的命令行接口 (CLIs, Command-line Interfaces)— Go语言俱乐部{{end}}
修改成这个： 
{{define "title"}}Go 写的 CLI （Command-line Interface） — Go语言俱乐部{{end}}

2019-11-22 08:36 UTC, stayfoo commented on template/solutions/clis.html
> +        <p>CLIs（CLIs, Command-line Interfaces，命令行接口）与 GUIs（GUIs，graphical user interfaces，图形用户界面）不同，CLIs 是纯文本的。云计算和基础架构程序具有易于自动化和远程功能的特性，所以云计算和基础架构程序主要是基于 CLI 的。</p>
统一成 CLI ，修改成：

CLI（Command-line Interface）与 GUI（GUI，graphical user interface，图形用户界面）不同，CLI 是纯文本的。云计算和基础架构程序具有易于自动化和远程功能的特性，所以云计算和基础架构程序主要是基于 CLI 的。

2019-11-22 08:43 UTC, stayfoo commented on template/index.html
> +                    使用 Go 的一些流行的开源包，以及健壮的标准库， 创建快速、优雅的 CLIs (Command-line Interfaces, 命令行接口)。
统一成 CLI，修改成：
使用 Go 的一些流行的开源包，以及健壮的标准库， 创建快速、优雅的 CLI （Command-line Interface） 。

2019-11-22 17:25 UTC, unknwon commented on template/index.html
> +        “I started writing in Go when I was just out of college and couldn’t
这是还没有翻译完么

2019-11-25 11:29 UTC, stayfoo commented on template/index.html
> +        “I started writing in Go when I was just out of college and couldn’t
翻译完了，合并了，解了一下冲突

2019-11-25 17:53 UTC, unknwon requested changes

2019-11-25 17:53 UTC, unknwon commented on template/index.html
> +            使用 Go 的一些流行的开源包，以及健壮的标准库， 创建快速、优雅的 CLI （Command-line Interface） 。
```suggestion
            使用 Go 的一些流行的开源包，以及健壮的标准库，创建快速、优雅的 CLI（Command-line Interface） 。
```

2019-11-25 17:53 UTC, unknwon commented on template/index.html
> +          <a href="/solutions/clis/">更多 &gt;</a>
```suggestion
          <a href="/solutions/clis/">了解更多 &gt;</a>
```

2019-11-25 17:53 UTC, unknwon commented on template/solutions/clis.html
> +        <h1>Go 写的 CLI （Command-line Interface）</h1>
```suggestion
        <h1>Go 写的 CLI（Command-line Interface）</h1>
```

2019-11-25 17:53 UTC, unknwon commented on template/solutions/clis.html
> +        <h2 id="cli-developers-prefer-go-for-portability-performance-and-ease-of-creation">因为 Go 的可移植性、卓越的性能以及易于创建的特性，开发者更偏爱使用 Go 来开发 CLI 。 </h2>
```suggestion
        <h2 id="cli-developers-prefer-go-for-portability-performance-and-ease-of-creation">因为 Go 的可移植性、卓越的性能以及易于创建的特性，开发者更偏爱使用 Go 来开发 CLI。</h2>
```

2019-11-25 17:53 UTC, unknwon commented on template/solutions/clis.html
> +                优雅的设计让 Go 可以完美的适合多种应用风格，并且它能够很容易交叉编译成适合多平台的二进制，这让它具有很大的优势。”
怎么只有一个尾部的双引号。。是不是少了一个？

2019-11-25 17:53 UTC, unknwon commented on template/solutions/clis.html
> +        <p>CLI 开发者发现 Go 非常适合设计他们的应用程序。Go 项目能够很快地编译成一个单独的二进制文件，并且以一致的风格快平台工作，并且有一个强大的开发社区。 单单使用一台 Windows 电脑或者一台 Mac 笔记本电脑，开发者就能为几十种不同架构体系中的每一种架构构建一个 Go 应用程序，并且操作系统能在几秒钟内就能实现，不需要复杂的构建环境。其他任何编译语言都不可能如此
```suggestion
        <p>CLI 开发者发现 Go 非常适合设计他们的应用程序。Go 项目能够很快地编译成一个单独的二进制文件，并且以一致的风格快平台工作，并且有一个强大的开发社区。单单使用一台 Windows 电脑或者一台 Mac 笔记本电脑，开发者就能为几十种不同架构体系中的每一种架构构建一个 Go 应用程序，并且操作系统能在几秒钟内就能实现，不需要复杂的构建环境。其他任何编译语言都不可能如此迅速、也不可能具有如此的可移植性。Go 应用程序被构建成一个独立的二进制文件中，这使得 Go 应用程序安装变得非常简单。</p>
```

2019-11-25 17:53 UTC, unknwon commented on template/solutions/clis.html
> +        <p>更重要的是，<strong>用 Go 编写的程序可以在任何系统上运行，而不需要任何现有的库、运行时或依赖项 </strong>。 并且 <strong>Go 编写的程序有一个立即启动的时间</strong>—类似于 C 或 C++，但无法用其他编程语言获得。</p>
```suggestion
        <p>更重要的是，<strong>用 Go 编写的程序可以在任何系统上运行，而不需要任何现有的库、运行时或依赖项 </strong>。并且 <strong>Go 编写的程序有一个立即启动的时间</strong>—类似于 C 或 C++，但无法用其他编程语言获得。</p>
```

2019-11-25 17:53 UTC, unknwon commented on template/solutions/clis.html
> +                CLI 的最佳设计是使用可预测的、面向任务的命令，并且你想要使用 Go。
“并且你想要使用 Go” 感觉怪怪的。。原文是什么？

2019-11-25 17:53 UTC, unknwon commented on template/solutions/clis.html
> +                <p class="MediaList-itemBoxBody-top">GitHub <a href="https://github.com/github/hub" rel="noreferrer" target="_blank">使用 Go 开发命令行工具，</a> 这个可以让使用 GitHub 更容易， 封装 git ，以便使用额外的特性和命令对其进行扩展。
```suggestion
                <p class="MediaList-itemBoxBody-top">GitHub <a href="https://github.com/github/hub" rel="noreferrer" target="_blank">使用 Go 开发命令行工具，</a> 这个可以让使用 GitHub 更容易，封装 git，以便使用额外的特性和命令对其进行扩展。</p>
```

2019-11-25 17:53 UTC, unknwon commented on template/solutions/clis.html
> +                <p class="MediaList-itemBoxBody-top">Uber 使用 Go 开发了一些 CLI 工具， 包括<a href="https://www.jaegertracing.io/docs/1.14/cli/" rel="noreferrer" target="_blank">Jaeger 的 CLI API</a>，一个用于监控微服务分布
```suggestion
                <p class="MediaList-itemBoxBody-top">Uber 使用 Go 开发了一些 CLI 工具，包括<a href="https://www.jaegertracing.io/docs/1.14/cli/" rel="noreferrer" target="_blank">Jaeger 的 CLI API</a>，一个用于监控微服务分布式系统的分布式跟踪系统。</p>
```

2019-11-25 17:53 UTC, unknwon commented on template/solutions/clis.html
> +                <p class="MediaList-itemBoxBody-top">Stripe <a href="https://github.com/stripe/stripe-cli" rel="noreferrer" target="_blank">使用 Go 开发 Stripe 的 CLI 工具，</a> 用来帮助建立，测试和管理 Stripe integrati
```suggestion
                <p class="MediaList-itemBoxBody-top">Stripe <a href="https://github.com/stripe/stripe-cli" rel="noreferrer" target="_blank">使用 Go 开发 Stripe 的 CLI 工具，</a> 用来帮助建立，测试和管理 Stripe integration 的命令行权限。</p>
```

2019-11-25 17:53 UTC, unknwon commented on template/solutions/clis.html
> +            <a href="https://pkg.go.dev/github.com/spf13/cobra?tab=overview">Cobra</a> 既是一个创建强大的现代的 CLI 应用程序的库，也是一个使用 Go 生成普通应用程序和 CLI 应用程序的程序。Cobra 支持大多数流行的 Go 应用程序，包括 CoreOS， Delve， Docker， Dropbox
```suggestion
            <a href="https://pkg.go.dev/github.com/spf13/cobra?tab=overview">Cobra</a> 既是一个创建强大的现代的 CLI 应用程序的库，也是一个使用 Go 生成普通应用程序和 CLI 应用程序的程序。Cobra 支持大多数流行的 Go 应用程序，包括 CoreOS、Delve、Docker、Dropbox、Git LFS、Hugo、Kubernetes 以及 <a href="https://pkg.go.dev/github.com/spf13/cobra?tab=importedby" rel="noreferrer" target="_blank">其他更多</a>。使用集成的命令帮助，自动完成和文档 “这使得记录每个命令都变得非常简单，” <a href="https://blog.alexellis.io/5-keys-to-a-killer-go-cli/" rel="noreferrer" target="_blank">Alex Ellis</a> 说到，OpenFaaS 的创始人。
```

“使用集成的命令帮助，自动完成和文档”这个好像有点问题，原文是什么？

2019-11-26 02:15 UTC, stayfoo commented on template/solutions/clis.html
> +                优雅的设计让 Go 可以完美的适合多种应用风格，并且它能够很容易交叉编译成适合多平台的二进制，这让它具有很大的优势。”
前面使用的是 icon 前引号：
<div class="PullQuote-quoteHeader">
                <img class="PullQuote-image" src="/static/imgs/quote.svg" alt="Quotation mark.">
            </div>

2019-11-26 03:11 UTC, unknwon commented on template/solutions/clis.html
> +                优雅的设计让 Go 可以完美的适合多种应用风格，并且它能够很容易交叉编译成适合多平台的二进制，这让它具有很大的优势。”
OK!

2019-11-26 05:06 UTC, stayfoo commented on template/solutions/clis.html
> +        <p>CLI 开发者发现 Go 非常适合设计他们的应用程序。Go 项目能够很快地编译成一个单独的二进制文件，并且以一致的风格快平台工作，并且有一个强大的开发社区。 单单使用一台 Windows 电脑或者一台 Mac 笔记本电脑，开发者就能为几十种不同架构体系中的每一种架构构建一个 Go 应用程序，并且操作系统能在几秒钟内就能实现，不需要复杂的构建环境。其他任何编译语言都不可能如此
OK

2019-11-26 05:06 UTC, stayfoo commented on template/solutions/clis.html
> +        <h2 id="cli-developers-prefer-go-for-portability-performance-and-ease-of-creation">因为 Go 的可移植性、卓越的性能以及易于创建的特性，开发者更偏爱使用 Go 来开发 CLI 。 </h2>
已修改

2019-11-26 05:06 UTC, stayfoo commented on template/solutions/clis.html
> +        <h1>Go 写的 CLI （Command-line Interface）</h1>
已修改

2019-11-26 05:06 UTC, stayfoo commented on template/index.html
> +          <a href="/solutions/clis/">更多 &gt;</a>
已修改

2019-11-26 05:06 UTC, stayfoo commented on template/index.html
> +            使用 Go 的一些流行的开源包，以及健壮的标准库， 创建快速、优雅的 CLI （Command-line Interface） 。
已修改

2019-11-26 05:07 UTC, stayfoo commented on template/solutions/clis.html
> +        <p>更重要的是，<strong>用 Go 编写的程序可以在任何系统上运行，而不需要任何现有的库、运行时或依赖项 </strong>。 并且 <strong>Go 编写的程序有一个立即启动的时间</strong>—类似于 C 或 C++，但无法用其他编程语言获得。</p>
已修改

2019-11-26 05:10 UTC, stayfoo commented on template/solutions/clis.html
> +                <p class="MediaList-itemBoxBody-top">GitHub <a href="https://github.com/github/hub" rel="noreferrer" target="_blank">使用 Go 开发命令行工具，</a> 这个可以让使用 GitHub 更容易， 封装 git ，以便使用额外的特性和命令对其进行扩展。
已修改

2019-11-26 05:10 UTC, stayfoo commented on template/solutions/clis.html
> +                <p class="MediaList-itemBoxBody-top">Uber 使用 Go 开发了一些 CLI 工具， 包括<a href="https://www.jaegertracing.io/docs/1.14/cli/" rel="noreferrer" target="_blank">Jaeger 的 CLI API</a>，一个用于监控微服务分布
已修改

2019-11-26 05:11 UTC, stayfoo commented on template/solutions/clis.html
> +                <p class="MediaList-itemBoxBody-top">Stripe <a href="https://github.com/stripe/stripe-cli" rel="noreferrer" target="_blank">使用 Go 开发 Stripe 的 CLI 工具，</a> 用来帮助建立，测试和管理 Stripe integrati
已修改

2019-11-26 05:19 UTC, stayfoo commented on template/solutions/clis.html
> +            <a href="https://pkg.go.dev/github.com/spf13/cobra?tab=overview">Cobra</a> 既是一个创建强大的现代的 CLI 应用程序的库，也是一个使用 Go 生成普通应用程序和 CLI 应用程序的程序。Cobra 支持大多数流行的 Go 应用程序，包括 CoreOS， Delve， Docker， Dropbox
原文：
With integrated command help, autocomplete and documentation “[it] makes documenting each command really simple,” says Alex Ellis, founder of OpenFaaS.

修改成: 
有了集成的命令帮助、自动完成和文档化，"使每个命令的文档化变的非常简单"

2019-11-26 05:21 UTC, unknwon commented on template/solutions/clis.html
> +            <a href="https://pkg.go.dev/github.com/spf13/cobra?tab=overview">Cobra</a> 既是一个创建强大的现代的 CLI 应用程序的库，也是一个使用 Go 生成普通应用程序和 CLI 应用程序的程序。Cobra 支持大多数流行的 Go 应用程序，包括 CoreOS， Delve， Docker， Dropbox
好多了！

2019-11-26 05:21 UTC, unknwon commented
![image](https://user-images.githubusercontent.com/2946214/69601602-8c01e900-0fc9-11ea-81a7-9cfb6b887121.png)
修改好的点这个，界面显示的干净点

2019-11-26 05:24 UTC, stayfoo commented on template/solutions/clis.html
> +                CLI 的最佳设计是使用可预测的、面向任务的命令，并且你想要使用 Go。
原文：
CLIs are best designed with predictable, task-oriented commands and you want to use Go.
修改：
CLI 就是被用来设计使用可预测的、面向任务的命令，你肯定会希望使用 Go 来实现。

2019-11-26 05:28 UTC, stayfoo commented on template/solutions/clis.html
> +                CLI 的最佳设计是使用可预测的、面向任务的命令，并且你想要使用 Go。
由于 CLI 被用来设计可预测的、面向任务的命令，使用 Go 来实现是最好的。

2019-11-26 05:32 UTC, stayfoo commented
> ![image](https://user-images.githubusercontent.com/2946214/69601602-8c01e900-0fc9-11ea-81a7-9cfb6b887121.png)
> 修改好的点这个，界面显示的干净点

2019-11-26 05:34 UTC, unknwon commented
都改好了 request review 就可以了

2019-11-27 05:27 UTC, stayfoo commented
> e

都修改好了

2019-11-27 16:27 UTC, unknwon commented on template/solutions/clis.html
> +                <a href="https://medium.com/@skdomino/writing-better-clis-one-snake-at-a-time-d22e50e60056" target="_blank">&mdash; Steve Domino, 斯特拉拉高级工程师和设计师</a></div>
"斯特拉拉" 这个原文是啥，哈哈哈，好搞笑 😂

2019-11-27 16:28 UTC, unknwon commented on template/solutions/clis.html
> +            <a href="https://pkg.go.dev/github.com/spf13/cobra?tab=overview">Cobra</a> 既是一个创建强大的现代的 CLI 应用程序的库，也是一个使用 Go 生成普通应用程序和 CLI 应用程序的程序。Cobra 支持大多数流行的 Go 应用程序，包括 CoreOS、Delve、Docker、Dropbox、Gi
```suggestion
            <a href="https://pkg.go.dev/github.com/spf13/cobra?tab=overview">Cobra</a> 既是一个创建强大的现代的 CLI 应用程序的库，也是一个使用 Go 生成普通应用程序和 CLI 应用程序的程序。Cobra 支持大多数流行的 Go 应用程序，包括 CoreOS、Delve、Docker、Dropbox、Git LFS、Hugo、Kubernetes 以及 <a href="https://pkg.go.dev/github.com/spf13/cobra?tab=importedby" rel="noreferrer" target="_blank">其他更多</a>。有了集成的命令帮助、自动完成和文档化，“使每个命令的文档化变的非常简单，” <a href="https://blog.alexellis.io/5-keys-to-a-killer-go-cli/" rel="noreferrer" target="_blank">Alex Ellis</a> 说到，OpenFaaS 的创始人。
```

2019-11-27 16:28 UTC, unknwon commented on template/solutions/clis.html
> +        <p>&ldquo;如果你不想污染你的命令行工具，或者你正在处理敏感数据，不希望在历史记录中显示这些数据，使用环境变量来控制是一个好方法。对此，你可以使用 Viper，&rdquo; <a href="https://ordina-jworks.github.io/development/2018/10/20/make-your-own-cli-with-golang-and-c
"建议 Geudens"?

2019-11-28 06:00 UTC, stayfoo commented on template/solutions/clis.html
> +        <p>&ldquo;如果你不想污染你的命令行工具，或者你正在处理敏感数据，不希望在历史记录中显示这些数据，使用环境变量来控制是一个好方法。对此，你可以使用 Viper，&rdquo; <a href="https://ordina-jworks.github.io/development/2018/10/20/make-your-own-cli-with-golang-and-c
这里引用了 NICK GEUDENS 的一篇博客里面的话：
If you don’t want to pollute your command line, or if you’re working with sensitive data which you don’t want to show up in the history, it’s a good idea to work with environment variables. To do this, you can use Viper. 
--------------------------------------------------------
NICK GEUDENS 的 主页 https://ordina-jworks.github.io/author/nick-geudens/
引用的文章：https://ordina-jworks.github.io/development/2018/10/20/make-your-own-cli-with-golang-and-cobra.html

2019-11-28 06:04 UTC, stayfoo commented on template/solutions/clis.html
> +                <a href="https://medium.com/@skdomino/writing-better-clis-one-snake-at-a-time-d22e50e60056" target="_blank">&mdash; Steve Domino, 斯特拉拉高级工程师和设计师</a></div>
😂  公司名字 Strala 直接用英文了

2019-11-28 06:05 UTC, stayfoo commented on template/solutions/clis.html
> +        <p>&ldquo;如果你不想污染你的命令行工具，或者你正在处理敏感数据，不希望在历史记录中显示这些数据，使用环境变量来控制是一个好方法。对此，你可以使用 Viper，&rdquo; <a href="https://ordina-jworks.github.io/development/2018/10/20/make-your-own-cli-with-golang-and-c
Geudens 建议

读了一遍修改了一些不通顺的。

2019-11-28 06:06 UTC, stayfoo commented
真的需要多读两遍，自己都能读出不通顺的地方！！！

2019-11-28 06:44 UTC, unknwon approved these changes

2019-11-28 06:44 UTC, merged