【完成】翻译：Cloud & Network Services, fix#12
polaris1119/golangclub pull request #25
Opened 2019-11-22 15:23 UTC by ligexiao

@polaris1119 @unknwon 下图Cloud & Network Services部分翻译完成，增加了一个 /solutions/cloud/ 新页面
![image](https://user-images.githubusercontent.com/2442790/69437833-f83cdc80-0d7e-11ea-88e7-5cafe48eaf02.png)

2019-11-22 17:31 UTC, unknwon requested changes

2019-11-22 17:31 UTC, unknwon commented on template/solutions/cloud.html
> +                <a href="https://builtin.com/software-engineering-perspectives/golang-advantages" target="_blank">&mdash; Ruchi Malik, developer at Choozle</a></div>
```suggestion
                <a href="https://builtin.com/software-engineering-perspectives/golang-advantages" target="_blank">&mdash; Ruchi Malik，Choozle 工程师</a></div>
```

2019-11-22 17:31 UTC, unknwon commented on template/solutions/cloud.html
> +              <p class="MediaList-itemBoxBody-top">Google Cloud 内置了 Go。在 Google Cloud 中，横跨整个行业的许多关键的云项目如 <a href="https://kubernetes.io/" rel="noreferrer" target="_blank">Kubernetes</a>, <a href="htt
```suggestion
              <p class="MediaList-itemBoxBody-top">Google Cloud 内置了 Go。在 Google Cloud 中，横跨整个行业的许多关键的云项目如 <a href="https://kubernetes.io/" rel="noreferrer" target="_blank">Kubernetes</a>，<a href="https://istio.io/" rel="noreferrer" target="_blank">Istio</a> 和 <a href="https://gvisor.dev/" rel="noreferrer" target="_blank">gVisor</a> 均由 Go 编写。<a href="https://cloud.google.com" rel="noreferrer" target="_blank">Google Cloud</a> 上所有的 API 和运行时都完全支持 Go，包括无服务器 <a href="https://cloud.google.com/appengine/" rel="noreferrer" target="_blank">App Engine</a>, <a href="https://cloud.google.com/knative/" rel="noreferrer" target="_blank">Knative</a>，<a href="https://cloud.google.com/run/" rel="noreferrer" target="_blank">Cloud Run</a>，和 <a href="https://cloud.google.com/functions/" rel="noreferrer" target="_blank">Google Cloud Functions</a>。</p>
```

2019-11-22 17:31 UTC, unknwon commented on template/solutions/cloud.html
> +              <p class="MediaList-itemBoxBody-top">Uber 使用 Go 增加了几个关键服务，该服务影响者全世界范围的数百万司机与乘客。从他们的<a href="https://eng.uber.com/aresdb/" rel="noreferrer" target="_blank">实时分析引擎</a>（AresDB）到他们的<a href=
```suggestion
              <p class="MediaList-itemBoxBody-top">Uber 使用 Go 增加了几个关键服务，该服务影响者全世界范围的数百万司机与乘客。从他们的<a href="https://eng.uber.com/aresdb/" rel="noreferrer" target="_blank">实时分析引擎</a>（AresDB）到他们的<a href="https://eng.uber.com/go-geofence/" rel="noreferrer" target="_blank">查询地理位置的微服务</a>（Geofence）以及<a href="https://eng.uber.com/open-sourcing-peloton/" rel="noreferrer" target="_blank">他们的资源调度器</a>都是用 Go 来实现的。</p>
```

2019-11-22 17:31 UTC, unknwon commented on template/solutions/cloud.html
> +            <a href="https://pkg.go.dev/github.com/dgrijalva/jwt-go?tab=overview">dgrijalva/jwt-go</a>，jwt（Json Web Token）的Go 版本实现</li>
```suggestion
            <a href="https://pkg.go.dev/github.com/dgrijalva/jwt-go?tab=overview">dgrijalva/jwt-go</a>，JWT（Json Web Token）的 Go 版本实现</li>
```

2019-11-22 17:31 UTC, unknwon commented on template/solutions/cloud.html
> +            <li><a href="https://awesome-go.com/" rel="noreferrer" target="_blank">Awesome Go</a>，Go框架，库和软件的精选</li>
```suggestion
            <li><a href="https://awesome-go.com/" rel="noreferrer" target="_blank">Awesome Go</a>、Go框架、库和软件的精选</li>
```

2019-11-24 04:03 UTC, unknwon requested changes

2019-11-24 04:03 UTC, unknwon commented on template/index.html
> +        <h3 class="UseCase-title">云 &amp; 网络服务</h3>
```suggestion
        <h3 class="UseCase-title">云计算和网络服务</h3>
```

2019-11-24 04:03 UTC, unknwon commented on template/solutions/cloud.html
> +            <h1>Go 云 &amp; 网络服务</h1>
```suggestion
            <h1>云计算网络服务</h1>
```

2019-11-24 04:03 UTC, unknwon commented on template/solutions/cloud.html
> +              <p class="MediaList-itemBoxBody-top">Dropbox 之前由 Python 构建，<a href="https://blogs.dropbox.com/tech/2014/07/open-sourcing-our-go-libraries/" rel="noreferrer" target="_blank">但是在2013年决定</
```suggestion
              <p class="MediaList-itemBoxBody-top">Dropbox 之前由 Python 构建，<a href="https://blogs.dropbox.com/tech/2014/07/open-sourcing-our-go-libraries/" rel="noreferrer" target="_blank">但是在2013年决定</a> 将影响性能的模块迁移到 Go 上。今天公司的大部分基础设施是采用 Go 来构建。目前 GitHub 上有一些 <a href="https://github.com/dropbox/godropbox" rel="noreferrer" target="_blank">Dropbox 的开源库</a>。</p>
```

2019-11-24 04:03 UTC, unknwon commented on template/solutions/cloud.html
> +            <p><strong>Kubernetes 是一个用 Go 编写的开源的容器编排系统，可用于自动化 web 应用程序部署。</strong> Web 应用程序经常使用容器（正如上文提到的）打包他们的依赖与配置。Kubernetes 有助于大规模部署和管理这些容器。云程序员使用 Kubernetes 快速构建、交付和规模化容器化的应用程序，通过使用控制容器运行的 APIs
"云程序员" 是什么？

2019-11-24 04:03 UTC, unknwon commented on template/solutions/cloud.html
> +                <h3>云客户端库</h2>
```suggestion
                <h3>云计算客户端库</h2>
```

2019-11-24 04:07 UTC, ligexiao commented on template/solutions/cloud.html
> +            <p><strong>Kubernetes 是一个用 Go 编写的开源的容器编排系统，可用于自动化 web 应用程序部署。</strong> Web 应用程序经常使用容器（正如上文提到的）打包他们的依赖与配置。Kubernetes 有助于大规模部署和管理这些容器。云程序员使用 Kubernetes 快速构建、交付和规模化容器化的应用程序，通过使用控制容器运行的 APIs
这里直译了。。应该翻译为：云开发者 更为贴切...

2019-11-24 04:10 UTC, unknwon commented on template/solutions/cloud.html
> +            <p><strong>Kubernetes 是一个用 Go 编写的开源的容器编排系统，可用于自动化 web 应用程序部署。</strong> Web 应用程序经常使用容器（正如上文提到的）打包他们的依赖与配置。Kubernetes 有助于大规模部署和管理这些容器。云程序员使用 Kubernetes 快速构建、交付和规模化容器化的应用程序，通过使用控制容器运行的 APIs
“云服务开发者”咋样？

2019-11-24 04:13 UTC, ligexiao commented on template/solutions/cloud.html
> +                <h3>云客户端库</h2>
这里意译为『云服务客户端库』会不会更好点。因为『云计算』是一个泛称的概念，而这里客户端库是一个具体的东西。

2019-11-24 04:14 UTC, unknwon commented on template/solutions/cloud.html
> +                <h3>云客户端库</h2>
好的！

2019-11-24 04:19 UTC, ligexiao commented on template/solutions/cloud.html
> +            <p><strong>Kubernetes 是一个用 Go 编写的开源的容器编排系统，可用于自动化 web 应用程序部署。</strong> Web 应用程序经常使用容器（正如上文提到的）打包他们的依赖与配置。Kubernetes 有助于大规模部署和管理这些容器。云程序员使用 Kubernetes 快速构建、交付和规模化容器化的应用程序，通过使用控制容器运行的 APIs
很OK！

2019-11-28 11:33 UTC, polaris1119 requested changes
go 文件修改处理下。

2019-11-28 11:33 UTC, polaris1119 commented on http/controller/index.go
>  	e.GET("/solutions/:typ", i.solutionProxy)
以上的路由不需要。我特意做了一个通配：`e.GET("/solutions/:typ", i.solutionProxy)`，只需要在 template/solutions 下创建模板文件即可。

2019-11-28 11:33 UTC, polaris1119 commented on http/controller/index.go
> +
同上，去掉代码

2019-11-28 11:33 UTC, polaris1119 commented on http/controller/index.go
> +}
同上，去掉代码

2019-11-28 12:25 UTC, polaris1119 approved these changes

2019-11-28 12:25 UTC, merged