feat: 完成关于的 About 部分翻译
polaris1119/golangclub pull request #29
Opened 2019-11-23 14:55 UTC by KowloonZh

Signed-off-by: zhangjiulong <kowloonzh@gmail.com>

2019-11-24 03:59 UTC, unknwon requested changes

2019-11-24 03:59 UTC, unknwon commented on template/about.html
> +    <p><a href="https://golangclub.com/" rel="noreferrer" target="_blank">Go 语言俱乐部</a> 是 <a href="https://studygolang.com" rel="noreferrer" target="_blank">Go 语言中文网</a> 的姊妹网站，是 <a href="https://go.de
"姊妹网站" 听起来怪怪。。我觉得直接说是 Go 语言中文网发起的吧？

2019-11-24 03:59 UTC, unknwon commented on template/about.html
> +        Go 语言俱乐部提供:</p>
```suggestion
        Go 语言俱乐部提供：</p>
```

2019-11-24 03:59 UTC, unknwon commented on template/about.html
> +        <li>集中展示发布在 index.golang.org. 的 Go 包和模块信息</li>
```suggestion
        <li>集中展示发布在 index.golang.org 的 Go 包和模块信息</li>
```

2019-11-24 08:28 UTC, KowloonZh commented on template/about.html
> +    <p><a href="https://golangclub.com/" rel="noreferrer" target="_blank">Go 语言俱乐部</a> 是 <a href="https://studygolang.com" rel="noreferrer" target="_blank">Go 语言中文网</a> 的姊妹网站，是 <a href="https://go.de
已修改，辛苦无闻兄再 review 一下

2019-11-24 20:52 UTC, unknwon commented on template/about.html
> +    <p><a href="https://golangclub.com/" rel="noreferrer" target="_blank">Go 语言俱乐部</a> 是 <a href="https://go.dev" rel="noreferrer" target="_blank">Go.dev</a> 的中国本土化，由 <a href="https://studygolang.com
```suggestion
    <p><a href="https://golangclub.com/" rel="noreferrer" target="_blank">Go 语言俱乐部</a> 是 <a href="https://go.dev" rel="noreferrer" target="_blank">Go.dev</a> 的中国本土化站点，由 <a href="https://studygolang.com" rel="noreferrer" target="_blank">Go 语言中文网</a> 发起。 Go 语言中文网是 Go 语言爱好者分享 Go 语言知识，交流使用经验的学习家园，而 Go 语言俱乐部是 Go 语言爱好者的中心，提供来自整个 Go 生态系统的集中和策划的资源。</p>
```

2019-11-24 20:53 UTC, unknwon commented on template/about.html
> +    <p><a href="https://golangclub.com/" rel="noreferrer" target="_blank">Go 语言俱乐部</a> 是 <a href="https://go.dev" rel="noreferrer" target="_blank">Go.dev</a> 的中国本土化，由 <a href="https://studygolang.com
这就一个问题了应该

2019-11-28 06:26 UTC, unknwon approved these changes

2019-11-28 06:26 UTC, merged